/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class swordbearer_audio_AudioCodec */

#ifndef _Included_swordbearer_audio_AudioCodec
#define _Included_swordbearer_audio_AudioCodec
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     swordbearer_audio_AudioCodec
 * Method:    audio_codec_init
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_swordbearer_audio_AudioCodec_audio_1codec_1init
  (JNIEnv *, jclass, jint);

/*
 * Class:     swordbearer_audio_AudioCodec
 * Method:    audio_encode
 * Signature: ([BII[BI)I
 */
JNIEXPORT jint JNICALL Java_swordbearer_audio_AudioCodec_audio_1encode
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray, jint);

/*
 * Class:     swordbearer_audio_AudioCodec
 * Method:    audio_decode
 * Signature: ([BII[BI)I
 */
JNIEXPORT jint JNICALL Java_swordbearer_audio_AudioCodec_audio_1decode
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
